/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/Tabs/About.vue')['default']
    Address: typeof import('./src/components/Tabs/ConfigItem/Address.vue')['default']
    AI: typeof import('./src/components/Tabs/AI.vue')['default']
    Alert: typeof import('./src/components/Alert.vue')['default']
    Appearance: typeof import('./src/components/Tabs/ConfigItem/Appearance.vue')['default']
    ChatBox: typeof import('./src/components/ChatBox.vue')['default']
    Config: typeof import('./src/components/Tabs/Config.vue')['default']
    ConfigItem: typeof import('./src/components/Tabs/ConfigItem/ConfigItem.vue')['default']
    CustomGreeting: typeof import('./src/components/Tabs/ConfigItem/CustomGreeting.vue')['default']
    Filter: typeof import('./src/components/Tabs/Filter.vue')['default']
    FormItem: typeof import('./src/components/Tabs/ConfigItem/Form/FormItem.vue')['default']
    FormSelect: typeof import('./src/components/Tabs/ConfigItem/Form/FormSelect.vue')['default']
    FormSwitch: typeof import('./src/components/Tabs/ConfigItem/Form/FormSwitch.vue')['default']
    JobCard: typeof import('./src/components/JobCard.vue')['default']
    JobCards: typeof import('./src/components/JobCards.vue')['default']
    LLMForm: typeof import('./src/components/AI/LLMForm.vue')['default']
    LLMFormItem: typeof import('./src/components/AI/LLMFormItem.vue')['default']
    LLMModelEdit: typeof import('./src/components/AI/LLMModelEdit.vue')['default']
    LLMModelManage: typeof import('./src/components/AI/LLMModelManage.vue')['default']
    LLMPromptEdit: typeof import('./src/components/AI/LLMPromptEdit.vue')['default']
    Log: typeof import('./src/components/Menu/Log.vue')['default']
    Logs: typeof import('./src/components/Tabs/Logs.vue')['default']
    SalaryRange: typeof import('./src/components/Tabs/ConfigItem/SalaryRange.vue')['default']
    SalaryRangeInput: typeof import('./src/components/Tabs/ConfigItem/Form/SalaryRangeInput.vue')['default']
    Statistics: typeof import('./src/components/Tabs/Statistics.vue')['default']
    Store: typeof import('./src/components/Menu/Store.vue')['default']
    Version: typeof import('./src/components/Menu/Version.vue')['default']
  }
}

// For TSX support
declare global {
  const About: typeof import('./src/components/Tabs/About.vue')['default']
  const Address: typeof import('./src/components/Tabs/ConfigItem/Address.vue')['default']
  const AI: typeof import('./src/components/Tabs/AI.vue')['default']
  const Alert: typeof import('./src/components/Alert.vue')['default']
  const Appearance: typeof import('./src/components/Tabs/ConfigItem/Appearance.vue')['default']
  const ChatBox: typeof import('./src/components/ChatBox.vue')['default']
  const Config: typeof import('./src/components/Tabs/Config.vue')['default']
  const ConfigItem: typeof import('./src/components/Tabs/ConfigItem/ConfigItem.vue')['default']
  const CustomGreeting: typeof import('./src/components/Tabs/ConfigItem/CustomGreeting.vue')['default']
  const Filter: typeof import('./src/components/Tabs/Filter.vue')['default']
  const FormItem: typeof import('./src/components/Tabs/ConfigItem/Form/FormItem.vue')['default']
  const FormSelect: typeof import('./src/components/Tabs/ConfigItem/Form/FormSelect.vue')['default']
  const FormSwitch: typeof import('./src/components/Tabs/ConfigItem/Form/FormSwitch.vue')['default']
  const JobCard: typeof import('./src/components/JobCard.vue')['default']
  const JobCards: typeof import('./src/components/JobCards.vue')['default']
  const LLMForm: typeof import('./src/components/AI/LLMForm.vue')['default']
  const LLMFormItem: typeof import('./src/components/AI/LLMFormItem.vue')['default']
  const LLMModelEdit: typeof import('./src/components/AI/LLMModelEdit.vue')['default']
  const LLMModelManage: typeof import('./src/components/AI/LLMModelManage.vue')['default']
  const LLMPromptEdit: typeof import('./src/components/AI/LLMPromptEdit.vue')['default']
  const Log: typeof import('./src/components/Menu/Log.vue')['default']
  const Logs: typeof import('./src/components/Tabs/Logs.vue')['default']
  const SalaryRange: typeof import('./src/components/Tabs/ConfigItem/SalaryRange.vue')['default']
  const SalaryRangeInput: typeof import('./src/components/Tabs/ConfigItem/Form/SalaryRangeInput.vue')['default']
  const Statistics: typeof import('./src/components/Tabs/Statistics.vue')['default']
  const Store: typeof import('./src/components/Menu/Store.vue')['default']
  const Version: typeof import('./src/components/Menu/Version.vue')['default']
}